import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4']);

import { Alegreya, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const sourceSansPro = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-source-sans",
  weight: ["400", "500", "600", "700"],
});

const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-alegreya",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${sourceSansPro.variable} ${alegreya.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          {children}
          <ToastContainer />
        </main>
      </body>
    </html>
  );
}